const apiData = {
  api: [{
      params: "参数",
      desc: "说明",
      type: "类型",
      default: "默认值"
    },
    {
      params: "name",
      desc: "图标名称	",
      type: "String",
      default: "-"
    },
    {
      params: "info",
      desc: "图标右上角提示信息",
      type: "String| Number",
      default: "-"
    },
    {
      params: "color",
      desc: "图标颜色",
      type: "String",
      default: "inherit"
    },
    {
      params: "size",
      desc: "图标大小，如 20px，2em",
      type: "String",
      default: "inherit"
    },
    {
      params: "custom-style",
      desc: "自定义样式",
      type: "String",
      default: "-"
    },
    {
      params: "class-prefix",
      desc: "类名前缀",
      type: "String",
      default: "van-icon"
    }
  ],
  event: [{
      params: "方法名",
      desc: "说明",
      return: "返回值"
    },
    {
      params: "click",
      desc: "按钮点击事件回调",
      return: "-"
    }
  ],
  slot: [{
      params: "插槽",
      desc: "说明"
    },
    {
      params: "~",
      desc: "图片插槽,自定义icon的图标"
    }
  ],
  custom_class: [{
      params: "类名",
      desc: "说明"
    },
    {
      params: "custom-class",
      desc: "根节点样式类"
    }
  ],
  icon_name_list: {
    basic: [
      "success",
      "plus",
      "cross",
      "fail",
      "arrow",
      "arrow-left",
      "arrow-up",
      "arrow-down"
    ],
    filled: [
      "location",
      "like",
      "star",
      "phone",
      "setting",
      "fire",
      "coupon",
      "cart",
      "shopping-cart",
      "todo-list",
      "friends",
      "comment",
      "gem",
      "gift",
      "point-gift",
      "send-gift",
      "service",
      "bag",
      "expand",
      "balance-list",
      "medel",
      "clear",
      "clock",
      "question",
      "checked",
      "add",
      "gold-coin",
      "info",
      "manager",
      "label",
      "hot-sale",
      "hot",
      "new-arrival",
      "shop-collect",
      "goods-collect",
      "eye",
      "browsing-history",
      "bookmark",
      "bill",
      "video",
      "shop",
      "chat",
      "smile-comment",
      "vip-card",
      "award",
      "diamond",
      "volume",
      "cluster",
      "underway",
      "photo",
      "gift-card",
      "more",
      "alipay",
      "wechat",
      "photograph",
      "youzan-shield",
      "umbrella-circle",
      "bell",
      "printer",
      "map-marked",
      "card",
      "add-square",
      "new"
    ],
    full: ["location-o",
      "like-o",
      "star-o",
      "phone-o",
      "setting-o",
      "fire-o",
      "coupon-o",
      "cart-o",
      "shopping-cart-o",
      "todo-list-o",
      "friends-o",
      "comment-o",
      "gem-o",
      "gift-o",
      "point-gift-o",
      "send-gift-o",
      "service-o",
      "bag-o",
      "expand-o",
      "balance-list-o",
      "medel-o",
      "close",
      "clock-o",
      "question-o",
      "passed",
      "add-o",
      "gold-coin-o",
      "info-o",
      "manager-o",
      "label-o",
      "hot-sale-o",
      "hot-o",
      "new-arrival-o",
      "shop-collect-o",
      "goods-collect-o",
      "eye-o",
      "browsing-history-o",
      "bookmark-o",
      "bill-o",
      "video-o",
      "shop-o",
      "chat-o",
      "smile-comment-o",
      "vip-card-o",
      "award-o",
      "diamond-o",
      "volume-o",
      "cluster-o",
      "underway-o",
      "photo-o",
      "gift-card-o",
      "more-o",
      "phone-circle-o",
      "smile-o",
      "music-o",
      "balance-o",
      "refund-o",
      "birthday-cake-o",
      "user-o",
      "thumb-circle-o",
      "orders-o",
      "tv-o",
      "envelop-o",
      "flag-o",
      "flower-o",
      "filter-o",
      "bar-chart-o",
      "chart-trending-o",
      "comment-circle-o",
      "brush-o",
      "bullhorn-o",
      "hotel-o",
      "cashier-o",
      "newspaper-o",
      "warn-o",
      "notes-o",
      "calender-o",
      "bulb-o",
      "user-circle-o",
      "desktop-o",
      "apps-o",
      "home-o",
      "share",
      "search",
      "points",
      "edit",
      "delete",
      "qr",
      "qr-invalid",
      "closed-eye",
      "wap-home",
      "scan",
      "play",
      "pause",
      "stop",
      "free-postage",
      "certificate",
      "logistics",
      "contact",
      "cash-back-record",
      "after-sale",
      "exchange",
      "upgrade",
      "bars",
      "wap-nav",
      "ellipsis",
      "circle",
      "description",
      "records",
      "sign",
      "completed",
      "failure",
      "ecard-pay",
      "peer-pay",
      "balance-pay",
      "credit-pay",
      "debit-pay",
      "cash-on-deliver",
      "other-pay",
      "tosend",
      "pending-payment",
      "paid",
      "aim",
      "discount",
      "idcard"
    ]
  },




}



export default apiData;
