exports.privKey = `-----BEGIN RSA PRIVATE KEY-----
MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEA4vVjck8c0lyFZvIB
ZMLxhGvCLKUCTmCJlpjlM+9yPgtCQhLFjxYeeJnfd6Z+pIjzbgPM9nzaPSk8poPC
nZfxZQIDAQABAkA66BoBp0sBxoXRbGq0LmzlQ9rIH6Pzl9beQZzr1/A87c3U3XU9
xx+PYGbXXl7gdD8JG6UeXittqQScIeSveGbZAiEA/2WoJzb1hjiMUH9I2lttKoMF
Q2WeTd5Ze0AE+z9emf8CIQDjfoui9gawSuO3XiVCx4qe2RMXm3moCOZL18D0zGdM
mwIgBgBZhzJfapwBkBKtn5PuaMVTZlYI9kN3TtIeS9kdW/kCIQDZHYYBElMR33dz
Irvm/u/SaJQrHKw/7bZ1PcWfHJGd7wIgNRHWffncEcsSXgltIEt9wIb4uYcOPQDn
PHhldgi4Rag=
-----END RSA PRIVATE KEY-----
`;

exports.pubKey = `-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOL1Y3JPHNJchWbyAWTC8YRrwiylAk5g
iZaY5TPvcj4LQkISxY8WHniZ33emfqSI824DzPZ82j0pPKaDwp2X8WUCAwEAAQ==
-----END PUBLIC KEY-----
`;