exports.pubKey = `-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAOL1Y3JPHNJchWbyAWTC8YRrwiylAk5g
iZaY5TPvcj4LQkISxY8WHniZ33emfqSI824DzPZ82j0pPKaDwp2X8WUCAwEAAQ==
-----END PUBLIC KEY-----
`;